from Bot.version_number_updater import version_number_updater

version_updater = version_number_updater()
runes_version_num = version_updater.get_version_number()

primary_rune_tree_img = {
    'precision': f'//opgg-static.akamaized.net/images/lol/perkStyle/8000.png?image=q_auto:best&v={runes_version_num}',
    'domination': f'//opgg-static.akamaized.net/images/lol/perkStyle/8100.png?image=q_auto:best&v={runes_version_num}',
    'sorcery': f'//opgg-static.akamaized.net/images/lol/perkStyle/8200.png?image=q_auto:best&v={runes_version_num}',
    'resolve': f'//opgg-static.akamaized.net/images/lol/perkStyle/8400.png?image=q_auto:best&v={runes_version_num}',
    'inspiration': f'//opgg-static.akamaized.net/images/lol/perkStyle/8300.png?image=q_auto:best&v={runes_version_num}'
}

keystones_img = {
    'fleet': f'//opgg-static.akamaized.net/images/lol/perk/8021.png?image=q_auto:best&v={runes_version_num}',
    'conqueror': f'//opgg-static.akamaized.net/images/lol/perk/8010.png?image=q_auto:best&v={runes_version_num}',
    'pta': f'//opgg-static.akamaized.net/images/lol/perk/8005.png?image=q_auto:best&v={runes_version_num}',
    'lethal_tempo': f'//opgg-static.akamaized.net/images/lol/perk/8008.png?image=q_auto:best&v={runes_version_num}',
    'hob': f'//opgg-static.akamaized.net/images/lol/perk/9923.png?image=q_auto:best&v={runes_version_num}',
    'electrocute': f'//opgg-static.akamaized.net/images/lol/perk/8112.png?image=q_auto:best&v={runes_version_num}',
    'predator': f'//opgg-static.akamaized.net/images/lol/perk/8124.png?image=q_auto:best&v={runes_version_num}',
    'dh': f'//opgg-static.akamaized.net/images/lol/perk/8128.png?image=q_auto:best&v={runes_version_num}',
    'comet': f'//opgg-static.akamaized.net/images/lol/perk/8229.png?image=q_auto:best&v={runes_version_num}',
    'aery': f'//opgg-static.akamaized.net/images/lol/perk/8214.png?image=q_auto:best&v={runes_version_num}',
    'phase_rush': f'//opgg-static.akamaized.net/images/lol/perk/8230.png?image=q_auto:best&v={runes_version_num}',
    'grasp': f'//opgg-static.akamaized.net/images/lol/perk/8437.png?image=q_auto:best&v={runes_version_num}',
    'aftershock': f'//opgg-static.akamaized.net/images/lol/perk/8439.png?image=q_auto:best&v={runes_version_num}',
    'guardian': f'//opgg-static.akamaized.net/images/lol/perk/8465.png?image=q_auto:best&v={runes_version_num}',
    'glacial': f'//opgg-static.akamaized.net/images/lol/perk/8351.png?image=q_auto:best&v={runes_version_num}',
    'spellbook': f'//opgg-static.akamaized.net/images/lol/perk/8360.png?image=q_auto:best&v={runes_version_num}',
    'omnistone': f'//opgg-static.akamaized.net/images/lol/perk/8358.png?image=q_auto:best&v={runes_version_num}'
}

rune1_img = {
    'overheal': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    'triumph': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    'pom': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    'cheapshot': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    'tob': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    'sudden_impact': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    'orb': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    'manaflow': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    'nimbus': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    'demolish': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    'font_of_life': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    'shield_bash': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    'hexflash': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    'footwear': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    'stopwatch': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}'
}

rune2_img = {
    'alacrity': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    'tenacity': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    'bloodline': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    'zombie_ward': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    'ghost_poro': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    'eyeball': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    'transcendence': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    'celerity': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    'focus': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    'conditioning': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    'second_wind': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    'boneplating': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    'future': f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    'minion': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    'biscuit': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}'
}

rune3_img = {
    'coup': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    'cut_down': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    'last_stand': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    'ravenous': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    'ingenious': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    'relentless': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    'ultimate': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    'scorch': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    'water_walking': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    'gathering_storm': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    'overgrowth': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    'revitalize': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    'unflinching': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    'cosmic': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    'approach_velocity': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    'timewarp': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}

######################################################
primary_rune_tree_emoji = {
    '<:precision:792162680369971261>': f'//opgg-static.akamaized.net/images/lol/perkStyle/8000.png?image=q_auto:best&v={runes_version_num}',
    '<:domination:792414255214493716>': f'//opgg-static.akamaized.net/images/lol/perkStyle/8100.png?image=q_auto:best&v={runes_version_num}',
    '<:sorcery:792441210152288256>': f'//opgg-static.akamaized.net/images/lol/perkStyle/8200.png?image=q_auto:best&v={runes_version_num}',
    '<:resolve:792421207949312020>': f'//opgg-static.akamaized.net/images/lol/perkStyle/8400.png?image=q_auto:best&v={runes_version_num}',
    '<:inspiration:792420733887709224>': f'//opgg-static.akamaized.net/images/lol/perkStyle/8300.png?image=q_auto:best&v={runes_version_num}'
}

keystones_emoji = {
    '<:FleetFootwork:792169831943503923>': f'//opgg-static.akamaized.net/images/lol/perk/8021.png?image=q_auto:best&v={runes_version_num}',
    '<:Conqueror:792169654340419654>': f'//opgg-static.akamaized.net/images/lol/perk/8010.png?image=q_auto:best&v={runes_version_num}',
    '<:pta:792175571857571841>': f'//opgg-static.akamaized.net/images/lol/perk/8005.png?image=q_auto:best&v={runes_version_num}',
    '<:lt:792413035187798047>': f'//opgg-static.akamaized.net/images/lol/perk/8008.png?image=q_auto:best&v={runes_version_num}',
    '<:hob:792415338142367774>': f'//opgg-static.akamaized.net/images/lol/perk/9923.png?image=q_auto:best&v={runes_version_num}',
    '<:electrocute:792415844625547305>': f'//opgg-static.akamaized.net/images/lol/perk/8112.png?image=q_auto:best&v={runes_version_num}',
    '<:predator:792417169086218280>': f'//opgg-static.akamaized.net/images/lol/perk/8124.png?image=q_auto:best&v={runes_version_num}',
    '<:dh:792417673408413728>': f'//opgg-static.akamaized.net/images/lol/perk/8128.png?image=q_auto:best&v={runes_version_num}',
    '<:aery:792419580969746482>': f'//opgg-static.akamaized.net/images/lol/perk/8214.png?image=q_auto:best&v={runes_version_num}',
    '<:comet1:792419590751256597>': f'//opgg-static.akamaized.net/images/lol/perk/8229.png?image=q_auto:best&v={runes_version_num}',
    '<:phaserush:792419599215624243>': f'//opgg-static.akamaized.net/images/lol/perk/8230.png?image=q_auto:best&v={runes_version_num}',
    '<:grasp:792422018187264020>': f'//opgg-static.akamaized.net/images/lol/perk/8437.png?image=q_auto:best&v={runes_version_num}',
    '<:aftershock:792422039952556062>': f'//opgg-static.akamaized.net/images/lol/perk/8439.png?image=q_auto:best&v={runes_version_num}',
    '<:guardian:792422039411490858>': f'//opgg-static.akamaized.net/images/lol/perk/8465.png?image=q_auto:best&v={runes_version_num}',
    '<:glacial:792423350667706368>': f'//opgg-static.akamaized.net/images/lol/perk/8351.png?image=q_auto:best&v={runes_version_num}',
    '<:spellbook:792423350956982302>': f'//opgg-static.akamaized.net/images/lol/perk/8360.png?image=q_auto:best&v={runes_version_num}',
    '<:omnistone:792423350609510449>': f'//opgg-static.akamaized.net/images/lol/perk/8358.png?image=q_auto:best&v={runes_version_num}'
}

rune1_emoji = {
    '<:overheal:792426715120140288>': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    '<:triumph1:792426714973208597>': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    '<:pom:792426715217002526>': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    '<:cheapshot:792442972620455947>': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    '<:tob:792442972855074826>': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    '<:suddenimpact:792442972875653140>': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    '<:orb:792454318623555594>': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    '<:manaflow:792454318032420874>': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    '<:nimbus:792454318191149136>': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    '<:demolish:792457268523696128>': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    '<:fontoflife:792457268100202527>': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    '<:shieldbash:792457268637204490>': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    '<:hexflash:792458707744980993>': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    '<:footwear:792458707794788372>': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    '<:stopwatch1:792458707509968936>': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}'
}

rune2_emoji = {
    '<:alacrity:792429210035159073>': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    '<:tenacity:792429212383969311>': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    '<:bloodline:792429210865631262>': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    '<:zombieward:792456100011573278>': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    '<:ghostporo:792456099886399488>': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    '<:eyeball:792456099709452338>': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    '<:transcendence:792454318422753311>': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    '<:celerity:792454317877493810>': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    '<:focus:792454317571440662>': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    '<:conditioning:792457267990495304>': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    '<:secondwind:792457268624490556>': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    '<:boneplating:792457267932692511>': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    '<:future:792458707467894794>': f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    '<:minion:792458707295535136>': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    '<:biscuit:792458706511069254>': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}'
}

rune3_emoji = {
    '<:coup:792430510512406619>': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    '<:cutdown:792430510806007838>': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    '<:laststand:792430510390509570>': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    '<:ravenous:792455662692073472>': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    '<:ingenious:792455662604648448>': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    '<:relentless:792455662595866654>': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    '<:ultimate:792455662659567647>': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    '<:scorch:792454318317633586>': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    '<:waterwalking:792454318028619814>': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    '<:gatheringstorm:792454317915373568>': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    '<:overgrowth:792457268293664779>': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    '<:revitalize:792457268507312148>': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    '<:unflinching:792457268499054631>': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    '<:cosmic:792458706646073384>': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    '<:approachvelocity:792458706468995103>': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    '<:timewarp:792458707023691776>': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}

######################################################
tree_names = {
    'Precision': f'//opgg-static.akamaized.net/images/lol/perkStyle/8000.png?image=q_auto:best&v={runes_version_num}',
    'Domination': f'//opgg-static.akamaized.net/images/lol/perkStyle/8100.png?image=q_auto:best&v={runes_version_num}',
    'Sorcery': f'//opgg-static.akamaized.net/images/lol/perkStyle/8200.png?image=q_auto:best&v={runes_version_num}',
    'Resolve': f'//opgg-static.akamaized.net/images/lol/perkStyle/8400.png?image=q_auto:best&v={runes_version_num}',
    'Inspiration': f'//opgg-static.akamaized.net/images/lol/perkStyle/8300.png?image=q_auto:best&v={runes_version_num}'
}

keystone_names = {
    'Fleet Footwork': f'//opgg-static.akamaized.net/images/lol/perk/8021.png?image=q_auto:best&v={runes_version_num}',
    'Conqueror': f'//opgg-static.akamaized.net/images/lol/perk/8010.png?image=q_auto:best&v={runes_version_num}',
    'Press the Attack': f'//opgg-static.akamaized.net/images/lol/perk/8005.png?image=q_auto:best&v={runes_version_num}',
    'Lethal Tempo': f'//opgg-static.akamaized.net/images/lol/perk/8008.png?image=q_auto:best&v={runes_version_num}',
    'Hail of Blades': f'//opgg-static.akamaized.net/images/lol/perk/9923.png?image=q_auto:best&v={runes_version_num}',
    'Electrocute': f'//opgg-static.akamaized.net/images/lol/perk/8112.png?image=q_auto:best&v={runes_version_num}',
    'Predator': f'//opgg-static.akamaized.net/images/lol/perk/8124.png?image=q_auto:best&v={runes_version_num}',
    'Dark Harvest': f'//opgg-static.akamaized.net/images/lol/perk/8128.png?image=q_auto:best&v={runes_version_num}',
    'Arcane Comet': f'//opgg-static.akamaized.net/images/lol/perk/8229.png?image=q_auto:best&v={runes_version_num}',
    'Summon Aery': f'//opgg-static.akamaized.net/images/lol/perk/8214.png?image=q_auto:best&v={runes_version_num}',
    'Phase Rush': f'//opgg-static.akamaized.net/images/lol/perk/8230.png?image=q_auto:best&v={runes_version_num}',
    'Grasp of the Undying': f'//opgg-static.akamaized.net/images/lol/perk/8437.png?image=q_auto:best&v={runes_version_num}',
    'Aftershock': f'//opgg-static.akamaized.net/images/lol/perk/8439.png?image=q_auto:best&v={runes_version_num}',
    'Guardian': f'//opgg-static.akamaized.net/images/lol/perk/8465.png?image=q_auto:best&v={runes_version_num}',
    'Glacial Augment': f'//opgg-static.akamaized.net/images/lol/perk/8351.png?image=q_auto:best&v={runes_version_num}',
    'Unsealed Spellbook': f'//opgg-static.akamaized.net/images/lol/perk/8360.png?image=q_auto:best&v={runes_version_num}',
    'Prototype: fOmnistone': f'//opgg-static.akamaized.net/images/lol/perk/8358.png?image=q_auto:best&v={runes_version_num}'
}

rune1_names = {
    'Overheal': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    'Triumph': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    'Presence of Mind': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    'Cheap Shot': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    'Taste of Blood': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    'Sudden Impact': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    'Nullifying Orb': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    'Manaflow Band': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    'Nimbus Cloak': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    'Demolish': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    'Font of Life': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    'Shield Bash': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    'Hexflash Flashtraption': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    'Magical Footwear': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    'Perfect Timing': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}'
}

rune2_names = {
    'Legend: fAlacrity': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    'Legend: fTenacity': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    'Legend: fBloodline': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    'Zombie Ward': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    'Ghost Poro': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    'Eyeball Collection': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    'Transcendence': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    'Celerity': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    'Absolute Focus': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    'Conditioning': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    'Second Wind': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    'Bone Plating': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    "Future's Market": f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    'Minion Dematerializer': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    'Biscuit Delivery': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}'
}

rune3_names = {
    'Coup de Grace': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    'Cut Down': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    'Last Stand': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    'Ravenous Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    'Ingenious Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    'Relentless Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    'Ultimate Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    'Scorch': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    'Waterwalking': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    'Gathering Storm': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    'Overgrowth': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    'Revitalize': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    'Unflinching': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    'Cosmic Insight': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    'Approach Velocity': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    'Time Warp Tonic': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}

##############################
secondary_rune_tree_img = {
    'precision': f'//opgg-static.akamaized.net/images/lol/perkStyle/8000.png?image=q_auto:best&v={runes_version_num}',
    'domination': f'//opgg-static.akamaized.net/images/lol/perkStyle/8100.png?image=q_auto:best&v={runes_version_num}',
    'sorcery': f'//opgg-static.akamaized.net/images/lol/perkStyle/8200.png?image=q_auto:best&v={runes_version_num}',
    'resolve': f'//opgg-static.akamaized.net/images/lol/perkStyle/8400.png?image=q_auto:best&v={runes_version_num}',
    'inspiration': f'//opgg-static.akamaized.net/images/lol/perkStyle/8300.png?image=q_auto:best&v={runes_version_num}'
}

secondary_rune1 = {
    '<:overheal:792426715120140288>': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    '<:triumph1:792426714973208597>': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    '<:pom:792426715217002526>': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    '<:cheapshot:792442972620455947>': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    '<:tob:792442972855074826>': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    '<:suddenimpact:792442972875653140>': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    '<:orb:792454318623555594>': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    '<:manaflow:792454318032420874>': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    '<:nimbus:792454318191149136>': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    '<:demolish:792457268523696128>': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    '<:fontoflife:792457268100202527>': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    '<:shieldbash:792457268637204490>': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    '<:hexflash:792458707744980993>': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    '<:footwear:792458707794788372>': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    '<:stopwatch1:792458707509968936>': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}'
}

secondary_rune2 = {
    '<:overheal:792426715120140288>': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    '<:triumph1:792426714973208597>': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    '<:pom:792426715217002526>': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    '<:cheapshot:792442972620455947>': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    '<:tob:792442972855074826>': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    '<:suddenimpact:792442972875653140>': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    '<:orb:792454318623555594>': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    '<:manaflow:792454318032420874>': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    '<:nimbus:792454318191149136>': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    '<:demolish:792457268523696128>': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    '<:fontoflife:792457268100202527>': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    '<:shieldbash:792457268637204490>': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    '<:hexflash:792458707744980993>': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    '<:footwear:792458707794788372>': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    '<:stopwatch1:792458707509968936>': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}'
}
#####################
second1_img = {
    'overheal': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    'triumph': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    'pom': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    'cheapshot': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    'tob': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    'sudden_impact': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    'orb': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    'manaflow': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    'nimbus': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    'demolish': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    'font_of_life': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    'shield_bash': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    'hexflash': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    'footwear': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    'stopwatch': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}',
    'alacrity': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    'tenacity': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    'bloodline': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    'zombie_ward': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    'ghost_poro': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    'eyeball': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    'transcendence': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    'celerity': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    'focus': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    'conditioning': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    'second_wind': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    'boneplating': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    'future': f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    'minion': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    'biscuit': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}',
    'coup': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    'cut_down': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    'last_stand': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    'ravenous': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    'ingenious': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    'relentless': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    'ultimate': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    'scorch': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    'water_walking': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    'gathering_storm': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    'overgrowth': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    'revitalize': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    'unflinching': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    'cosmic': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    'approach_velocity': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    'timewarp': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}

second2_img = {
    'overheal': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    'triumph': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    'pom': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    'cheapshot': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    'tob': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    'sudden_impact': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    'orb': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    'manaflow': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    'nimbus': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    'demolish': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    'font_of_life': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    'shield_bash': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    'hexflash': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    'footwear': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    'stopwatch': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}',
    'alacrity': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    'tenacity': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    'bloodline': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    'zombie_ward': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    'ghost_poro': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    'eyeball': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    'transcendence': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    'celerity': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    'focus': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    'conditioning': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    'second_wind': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    'boneplating': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    'future': f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    'minion': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    'biscuit': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}',
    'coup': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    'cut_down': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    'last_stand': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    'ravenous': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    'ingenious': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    'relentless': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    'ultimate': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    'scorch': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    'water_walking': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    'gathering_storm': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    'overgrowth': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    'revitalize': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    'unflinching': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    'cosmic': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    'approach_velocity': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    'timewarp': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}

########################
second1_names = {
    'Overheal': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    'Triumph': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    'Presence of Mind': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    'Cheap Shot': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    'Taste of Blood': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    'Sudden Impact': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    'Nullifying Orb': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    'Manaflow Band': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    'Nimbus Cloak': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    'Demolish': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    'Font of Life': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    'Shield Bash': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    'Hexflash Flashtraption': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    'Magical Footwear': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    'Perfect Timing': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}',
    'Legend: fAlacrity': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    'Legend: fTenacity': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    'Legend: fBloodline': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    'Zombie Ward': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    'Ghost Poro': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    'Eyeball Collection': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    'Transcendence': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    'Celerity': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    'Absolute Focus': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    'Conditioning': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    'Second Wind': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    'Bone Plating': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    "Future's Market": f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    'Minion Dematerializer': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    'Biscuit Delivery': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}',
    'Coup de Grace': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    'Cut Down': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    'Last Stand': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    'Ravenous Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    'Ingenious Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    'Relentless Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    'Ultimate Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    'Scorch': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    'Waterwalking': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    'Gathering Storm': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    'Overgrowth': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    'Revitalize': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    'Unflinching': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    'Cosmic Insight': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    'Approach Velocity': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    'Time Warp Tonic': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}

second2_names = {
    'Overheal': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    'Triumph': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    'Presence of Mind': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    'Cheap Shot': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    'Taste of Blood': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    'Sudden Impact': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    'Nullifying Orb': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    'Manaflow Band': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    'Nimbus Cloak': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    'Demolish': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    'Font of Life': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    'Shield Bash': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    'Hexflash Flashtraption': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    'Magical Footwear': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    'Perfect Timing': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}',
    'Legend: fAlacrity': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    'Legend: fTenacity': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    'Legend: fBloodline': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    'Zombie Ward': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    'Ghost Poro': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    'Eyeball Collection': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    'Transcendence': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    'Celerity': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    'Absolute Focus': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    'Conditioning': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    'Second Wind': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    'Bone Plating': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    "Future's Market": f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    'Minion Dematerializer': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    'Biscuit Delivery': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}',
    'Coup de Grace': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    'Cut Down': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    'Last Stand': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    'Ravenous Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    'Ingenious Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    'Relentless Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    'Ultimate Hunter': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    'Scorch': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    'Waterwalking': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    'Gathering Storm': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    'Overgrowth': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    'Revitalize': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    'Unflinching': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    'Cosmic Insight': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    'Approach Velocity': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    'Time Warp Tonic': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}

###################################
second1_emoji = {
    '<:overheal:792426715120140288>': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    '<:triumph1:792426714973208597>': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    '<:pom:792426715217002526>': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    '<:cheapshot:792442972620455947>': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    '<:tob:792442972855074826>': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    '<:suddenimpact:792442972875653140>': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    '<:orb:792454318623555594>': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    '<:manaflow:792454318032420874>': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    '<:nimbus:792454318191149136>': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    '<:demolish:792457268523696128>': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    '<:fontoflife:792457268100202527>': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    '<:shieldbash:792457268637204490>': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    '<:hexflash:792458707744980993>': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    '<:footwear:792458707794788372>': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    '<:stopwatch1:792458707509968936>': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}',
    '<:alacrity:792429210035159073>': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    '<:tenacity:792429212383969311>': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    '<:bloodline:792429210865631262>': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    '<:zombieward:792456100011573278>': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    '<:ghostporo:792456099886399488>': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    '<:eyeball:792456099709452338>': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    '<:transcendence:792454318422753311>': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    '<:celerity:792454317877493810>': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    '<:focus:792454317571440662>': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    '<:conditioning:792457267990495304>': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    '<:secondwind:792457268624490556>': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    '<:boneplating:792457267932692511>': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    '<:future:792458707467894794>': f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    '<:minion:792458707295535136>': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    '<:biscuit:792458706511069254>': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}',
    '<:coup:792430510512406619>': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    '<:cutdown:792430510806007838>': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    '<:laststand:792430510390509570>': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    '<:ravenous:792455662692073472>': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    '<:ingenious:792455662604648448>': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    '<:relentless:792455662595866654>': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    '<:ultimate:792455662659567647>': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    '<:scorch:792454318317633586>': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    '<:waterwalking:792454318028619814>': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    '<:gatheringstorm:792454317915373568>': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    '<:overgrowth:792457268293664779>': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    '<:revitalize:792457268507312148>': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    '<:unflinching:792457268499054631>': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    '<:cosmic:792458706646073384>': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    '<:approachvelocity:792458706468995103>': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    '<:timewarp:792458707023691776>': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}

second2_emoji = {
    '<:overheal:792426715120140288>': f'//opgg-static.akamaized.net/images/lol/perk/9101.png?image=q_auto:best&v={runes_version_num}',
    '<:triumph1:792426714973208597>': f'//opgg-static.akamaized.net/images/lol/perk/9111.png?image=q_auto:best&v={runes_version_num}',
    '<:pom:792426715217002526>': f'//opgg-static.akamaized.net/images/lol/perk/8009.png?image=q_auto:best&v={runes_version_num}',
    '<:cheapshot:792442972620455947>': f'//opgg-static.akamaized.net/images/lol/perk/8126.png?image=q_auto:best&v={runes_version_num}',
    '<:tob:792442972855074826>': f'//opgg-static.akamaized.net/images/lol/perk/8139.png?image=q_auto:best&v={runes_version_num}',
    '<:suddenimpact:792442972875653140>': f'//opgg-static.akamaized.net/images/lol/perk/8143.png?image=q_auto:best&v={runes_version_num}',
    '<:orb:792454318623555594>': f'//opgg-static.akamaized.net/images/lol/perk/8224.png?image=q_auto:best&v={runes_version_num}',
    '<:manaflow:792454318032420874>': f'//opgg-static.akamaized.net/images/lol/perk/8226.png?image=q_auto:best&v={runes_version_num}',
    '<:nimbus:792454318191149136>': f'//opgg-static.akamaized.net/images/lol/perk/8275.png?image=q_auto:best&v={runes_version_num}',
    '<:demolish:792457268523696128>': f'//opgg-static.akamaized.net/images/lol/perk/8446.png?image=q_auto:best&v={runes_version_num}',
    '<:fontoflife:792457268100202527>': f'//opgg-static.akamaized.net/images/lol/perk/8463.png?image=q_auto:best&v={runes_version_num}',
    '<:shieldbash:792457268637204490>': f'//opgg-static.akamaized.net/images/lol/perk/8401.png?image=q_auto:best&v={runes_version_num}',
    '<:hexflash:792458707744980993>': f'//opgg-static.akamaized.net/images/lol/perk/8306.png?image=q_auto:best&v={runes_version_num}',
    '<:footwear:792458707794788372>': f'//opgg-static.akamaized.net/images/lol/perk/8304.png?image=q_auto:best&v={runes_version_num}',
    '<:stopwatch1:792458707509968936>': f'//opgg-static.akamaized.net/images/lol/perk/8313.png?image=q_auto:best&v={runes_version_num}',
    '<:alacrity:792429210035159073>': f'//opgg-static.akamaized.net/images/lol/perk/9104.png?image=q_auto:best&v={runes_version_num}',
    '<:tenacity:792429212383969311>': f'//opgg-static.akamaized.net/images/lol/perk/9105.png?image=q_auto:best&v={runes_version_num}',
    '<:bloodline:792429210865631262>': f'//opgg-static.akamaized.net/images/lol/perk/9103.png?image=q_auto:best&v={runes_version_num}',
    '<:zombieward:792456100011573278>': f'//opgg-static.akamaized.net/images/lol/perk/8136.png?image=q_auto:best&v={runes_version_num}',
    '<:ghostporo:792456099886399488>': f'//opgg-static.akamaized.net/images/lol/perk/8120.png?image=q_auto:best&v={runes_version_num}',
    '<:eyeball:792456099709452338>': f'//opgg-static.akamaized.net/images/lol/perk/8138.png?image=q_auto:best&v={runes_version_num}',
    '<:transcendence:792454318422753311>': f'//opgg-static.akamaized.net/images/lol/perk/8210.png?image=q_auto:best&v={runes_version_num}',
    '<:celerity:792454317877493810>': f'//opgg-static.akamaized.net/images/lol/perk/8234.png?image=q_auto:best&v={runes_version_num}',
    '<:focus:792454317571440662>': f'//opgg-static.akamaized.net/images/lol/perk/8233.png?image=q_auto:best&v={runes_version_num}',
    '<:conditioning:792457267990495304>': f'//opgg-static.akamaized.net/images/lol/perk/8429.png?image=q_auto:best&v={runes_version_num}',
    '<:secondwind:792457268624490556>': f'//opgg-static.akamaized.net/images/lol/perk/8444.png?image=q_auto:best&v={runes_version_num}',
    '<:boneplating:792457267932692511>': f'//opgg-static.akamaized.net/images/lol/perk/8473.png?image=q_auto:best&v={runes_version_num}',
    '<:future:792458707467894794>': f'//opgg-static.akamaized.net/images/lol/perk/8321.png?image=q_auto:best&v={runes_version_num}',
    '<:minion:792458707295535136>': f'//opgg-static.akamaized.net/images/lol/perk/8316.png?image=q_auto:best&v={runes_version_num}',
    '<:biscuit:792458706511069254>': f'//opgg-static.akamaized.net/images/lol/perk/8345.png?image=q_auto:best&v={runes_version_num}',
    '<:coup:792430510512406619>': f'//opgg-static.akamaized.net/images/lol/perk/8014.png?image=q_auto:best&v={runes_version_num}',
    '<:cutdown:792430510806007838>': f'//opgg-static.akamaized.net/images/lol/perk/8017.png?image=q_auto:best&v={runes_version_num}',
    '<:laststand:792430510390509570>': f'//opgg-static.akamaized.net/images/lol/perk/8299.png?image=q_auto:best&v={runes_version_num}',
    '<:ravenous:792455662692073472>': f'//opgg-static.akamaized.net/images/lol/perk/8135.png?image=q_auto:best&v={runes_version_num}',
    '<:ingenious:792455662604648448>': f'//opgg-static.akamaized.net/images/lol/perk/8134.png?image=q_auto:best&v={runes_version_num}',
    '<:relentless:792455662595866654>': f'//opgg-static.akamaized.net/images/lol/perk/8105.png?image=q_auto:best&v={runes_version_num}',
    '<:ultimate:792455662659567647>': f'//opgg-static.akamaized.net/images/lol/perk/8106.png?image=q_auto:best&v={runes_version_num}',
    '<:scorch:792454318317633586>': f'//opgg-static.akamaized.net/images/lol/perk/8237.png?image=q_auto:best&v={runes_version_num}',
    '<:waterwalking:792454318028619814>': f'//opgg-static.akamaized.net/images/lol/perk/8232.png?image=q_auto:best&v={runes_version_num}',
    '<:gatheringstorm:792454317915373568>': f'//opgg-static.akamaized.net/images/lol/perk/8236.png?image=q_auto:best&v={runes_version_num}',
    '<:overgrowth:792457268293664779>': f'//opgg-static.akamaized.net/images/lol/perk/8451.png?image=q_auto:best&v={runes_version_num}',
    '<:revitalize:792457268507312148>': f'//opgg-static.akamaized.net/images/lol/perk/8453.png?image=q_auto:best&v={runes_version_num}',
    '<:unflinching:792457268499054631>': f'//opgg-static.akamaized.net/images/lol/perk/8242.png?image=q_auto:best&v={runes_version_num}',
    '<:cosmic:792458706646073384>': f'//opgg-static.akamaized.net/images/lol/perk/8347.png?image=q_auto:best&v={runes_version_num}',
    '<:approachvelocity:792458706468995103>': f'//opgg-static.akamaized.net/images/lol/perk/8410.png?image=q_auto:best&v={runes_version_num}',
    '<:timewarp:792458707023691776>': f'//opgg-static.akamaized.net/images/lol/perk/8352.png?image=q_auto:best&v={runes_version_num}'
}